services:
  - type: web
    name: site-fe
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NPM_FLAGS
        value: --legacy-peer-deps